## Note about the code below
(1) Assign the petal length and petal width of the 150 flower samples to the feature matrix X
(2) Assign the corresponding class labels of the flower species to the vector y
(3) The Iris flow class names Iris-setosa, Iris-versicolor and Iris-virginica are already stored as integeres 0, 1, 2 respectively. 

In [1]:
from sklearn.datasets import fetch_mldata

mnist = fetch_mldata('MNIST original')
print(list(mnist.keys()))
print(mnist["DESCR"])
print(mnist.COL_NAMES)
print(mnist.target)
#print(mnist)
X_mnist, y_mnist = mnist["data"], mnist["target"]
print(X_mnist.shape)
print(y_mnist.shape)

/Users/hcao/anaconda/lib/python3.5/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function fetch_mldata is deprecated; fetch_mldata was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)
/Users/hcao/anaconda/lib/python3.5/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function mldata_filename is deprecated; mldata_filename was deprecated in version 0.20 and will be removed in version 0.22
  warnings.warn(msg, category=DeprecationWarning)


['DESCR', 'data', 'target', 'COL_NAMES']
mldata.org dataset: mnist-original
['label', 'data']
[ 0.  0.  0. ...,  9.  9.  9.]
(70000, 784)
(70000,)


In [75]:
from sklearn.datasets import fetch_mldata
#iris_data = fetch_mldata('iris')
#from sklearn import datasets
#import numpy as np 

iris = datasets.load_iris()
X = iris.data
y = iris.target 

print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [76]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X)
X_std = sc.transform(X)
print(X.mean())
print(X_std.mean())

3.4636666666666662
-1.3263464400855204e-15


In [77]:
import numpy as np
from sklearn.model_selection import train_test_split

X_tr, X_ts, y_tr, y_ts = train_test_split(X_std, y, test_size=0.3, random_state=1, stratify=y)
print('Label counts in y', np.bincount(y)) 
print('Label counts in y_train', np.bincount(y_tr))
print('Label counts in y_test', np.bincount(y_ts))
#print(np.unique(y), " y length", y)
#print(y_tr)
#print(y_ts)

Label counts in y [50 50 50]
Label counts in y_train [35 35 35]
Label counts in y_test [15 15 15]


In [78]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(max_iter=40, eta0=0.1, random_state=1)
ppn.fit(X_tr, y_tr)

Perceptron(alpha=0.0001, class_weight=None, eta0=0.1, fit_intercept=True,
      max_iter=40, n_iter=None, n_jobs=1, penalty=None, random_state=1,
      shuffle=True, tol=None, verbose=0, warm_start=False)

In [79]:
from sklearn.metrics import accuracy_score
y_pred=ppn.predict(X_ts) 
error = (y_ts!=y_pred).sum()
print('Misclassified samples: %d' %error)
print ('Accuracy: %0.2f' % accuracy_score(y_ts, y_pred))

Misclassified samples: 7
Accuracy: 0.84


# Examples
https://machinelearningmastery.com/get-your-hands-dirty-with-scikit-learn-now/

In [6]:
# Gaussian Naive Bayes
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
# load the iris datasets
dataset = datasets.load_iris()
# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(dataset.data, dataset.target)
print("Model", model)
# make predictions
expected = dataset.target
predicted = model.predict(dataset.data)
# summarize the fit of the model
print("report:\n" , metrics.classification_report(expected, predicted))
print("confusion_matrix:\n", metrics.confusion_matrix(expected, predicted))

Model GaussianNB(priors=None)
report:
              precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.94      0.94      0.94        50
          2       0.94      0.94      0.94        50

avg / total       0.96      0.96      0.96       150

confusion_matrix:
 [[50  0  0]
 [ 0 47  3]
 [ 0  3 47]]


# Naive Bayesian classifier
https://blog.sicara.com/naive-bayes-classifier-sklearn-python-example-tips-42d100429e44

In [ ]:
###########
#The following code was not tested. 
############
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB

# Importing dataset
data = pd.read_csv("data/train.csv")

# Convert categorical variable to numeric
data["Sex_cleaned"]=np.where(data["Sex"]=="male",0,1)
data["Embarked_cleaned"]=np.where(data["Embarked"]=="S",0,
                                  np.where(data["Embarked"]=="C",1,
                                           np.where(data["Embarked"]=="Q",2,3)
                                          )
                                 )
# Cleaning dataset of NaN
data=data[[
    "Survived",
    "Pclass",
    "Sex_cleaned",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked_cleaned"
]].dropna(axis=0, how='any')

# Split dataset in training and test datasets
X_train, X_test = train_test_split(data, test_size=0.5, random_state=int(time.time()))

#Instantiate the classifier
gnb = GaussianNB()
used_features =[
    "Pclass",
    "Sex_cleaned",
    "Age",
    "SibSp",
    "Parch",
    "Fare",
    "Embarked_cleaned"
]

# Train classifier
gnb.fit(
    X_train[used_features].values,
    X_train["Survived"]
)
y_pred = gnb.predict(X_test[used_features])

# Print results
print("Number of mislabeled points out of a total {} points : {}, performance {:05.2f}%"
      .format(
          X_test.shape[0],
          (X_test["Survived"] != y_pred).sum(),
          100*(1-(X_test["Survived"] != y_pred).sum()/X_test.shape[0])
))